name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

    - name: Build and tag the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/my-image-name:${{ github.sha }}

    - name: Push the Docker image to GitHub Container Registry
      run: docker push ghcr.io/${{ github.repository_owner }}/my-image-name:${{ github.sha }}
